export const layoutTokens = {
  page: {
    top: '6.5rem',
    topCompact: '5.5rem',
    bottom: '6rem',
    bottomLarge: '7rem',
    bottomCompact: '4.5rem',
    detailBottom: '5rem',
    detailBottomCompact: '4rem',
  },
  container: {
    narrow: '60rem',
    content: '70rem',
    wide: '75rem',
    viewport: '96vw',
    compactViewport: '94vw',
  },
  grid: {
    cardMinWidth: '17.5rem',
    gap: '1rem',
  },
  nav: {
    hiddenOffset: '-106px',
    mobilePanelTopOffset: '5.7rem',
    heightDesktop: '84px',
    heightMobile: '72px',
  },
} as const;

export const componentTokens = {
  home: {
    heroMinHeight: '122svh',
    heroMinHeightCompact: '112svh',
    heroBottom: '6rem',
    heroBottomCompact: '3.4rem',
    heroContentWidth: 'min(58rem, 92vw)',
    heroContentPadding: '2.5rem 1.75rem',
    heroContentPaddingCompact: '1.6rem 1.1rem',
    heroGlowWidth: 'min(72rem, 88vw)',
    heroGlowHeight: 'min(32rem, 56vw)',
    panelsTop: '-5.5rem',
    panelsTopCompact: '-2.8rem',
    panelsBottom: '0',
    panelsBottomCompact: '0',
    heroLeadSize: 'clamp(1rem, 1.6vw, 1.28rem)',
    panelTitleSize: 'clamp(1.2rem, 2vw, 1.72rem)',
    eyebrowTracking: '0.3rem',
    scrollHintSize: '0.66rem',
    panelTitleTracking: '0.06rem',
    panelTextMaxWidth: '42ch',
    panelMinHeight: '18rem',
    panelMinHeightCompact: '14rem',
  },
  card: {
    mediaMinHeight: '14rem',
    mediaMinHeightCompact: '12rem',
    descriptionGap: '0.8rem',
    descriptionPadding: '1.4rem 1.3rem 1.5rem',
    hoverLift: '-4px',
    titleSize: 'clamp(1.3rem, 1.8vw, 1.9rem)',
    metaSize: '0.72rem',
    metaTracking: '0.14rem',
    actionSize: '0.82rem',
    actionTracking: '0.08rem',
  },
  overlay: {
    sideRailWidth: '70px',
    contentWidthOffset: '140px',
    toastBottomOffset: '1rem',
    toastWidth: 'min(32rem, calc(100vw - 2rem))',
    toastMinHeight: '3rem',
    lightPadding: '1rem',
  },
  gallery: {
    tileMinWidth: '16rem',
    tileAspectPadding: '66%',
    topOffset: '2rem',
  },
  about: {
    heroGap: '1rem',
    heroMediaAspect: '5 / 6',
    heroMediaAspectCompact: '4 / 5',
    heroMediaMinHeight: '28rem',
    heroMediaMinHeightCompact: '16rem',
    sectionCardMinWidth: '18rem',
    valueCardMinWidth: '16rem',
  },
  contacts: {
    infoGridLeft: 'minmax(0, 0.86fr)',
    infoGridRight: 'minmax(0, 1.14fr)',
    heroBottom: '2.2rem',
    gridGap: '1.1rem',
    panelPadding: '1.7rem 1.4rem',
    panelPaddingCompact: '1.2rem 1rem',
    listGap: '0.9rem',
    actionGap: '0.7rem',
    stepSize: '2.15rem',
    formHintSize: '0.84rem',
  },
  surface: {
    softPadding: '1.45rem 1.35rem',
    mutedPadding: '1.35rem 1.25rem',
  },
  action: {
    smPadding: '0.62rem 1rem',
    mdPadding: '0.75rem 1.2rem',
    smSize: '0.8rem',
    mdSize: '0.84rem',
    smTracking: '0.06rem',
    mdTracking: '0.07rem',
    squareMinWidth: '9rem',
    squareMinHeight: '3rem',
    squareTracking: '0.04rem',
    hoverLiftPrimary: '-2px',
    hoverLiftDefault: '-1px',
  },
  form: {
    fieldMinHeight: '2.9rem',
    textareaMinHeight: '11rem',
    fieldPadding: '0.75rem',
    buttonMinWidth: '8.5rem',
    buttonTracking: '0.08rem',
    focusRingWidth: '3px',
  },
  nav: {
    brandTracking: '0.24rem',
    linkSizeDesktop: '0.92rem',
    linkSizeMobile: '1.15rem',
    linkTrackingDesktop: '0.05rem',
    linkTrackingMobile: '0.06rem',
    linkHeightDesktop: '2.35rem',
    linkHeightMobile: '2.8rem',
    linkPaddingDesktop: '0.5rem 0.75rem',
    linkPaddingMobile: '0.75rem 1rem',
  },
  footer: {
    titleTracking: '0.12rem',
    linkTracking: '0.06rem',
    footnoteTracking: '0.03rem',
  },
  detail: {
    headerBottom: '1.8rem',
    backMinWidth: '10.4rem',
    titleTop: '1rem',
    leadTop: '0.8rem',
    metaTop: '0.7rem',
    metaTracking: '0.08rem',
    metaSize: '0.75rem',
    gridGap: '1rem',
    mediaMinHeight: '24rem',
    mediaMinHeightCompact: '16rem',
    descriptionPadding: '1.4rem 1.5rem',
    descriptionHeadingTop: '1.1rem',
    descriptionHeadingBottom: '0.65rem',
    descriptionHeadingTracking: '0.04rem',
    paragraphSpacing: '0.75rem',
    listVerticalSpacing: '0.8rem',
    listIndent: '1.2rem',
    sectionTitleTracking: '0.08rem',
    sectionTitleBottom: '0.8rem',
    sectionTop: '2.2rem',
  },
  listing: {
    headerBottom: '2rem',
    ctaTop: '2rem',
    ctaTextMaxWidth: '44ch',
    ctaLinkMinWidth: '10.5rem',
  },
  iconButton: {
    size: '2.7rem',
    topOffset: '1.25rem',
    lineWidth: '1.3rem',
    lineThickness: '2px',
    lineTopStart: '0.86rem',
    lineTopCenter: '1.28rem',
    lineTopEnd: '1.7rem',
  },
} as const;

export const typographyTokens = {
  eyebrowSize: '0.76rem',
  labelStrong: '0.84rem',
  eyebrowTracking: '0.2rem',
  trackingTight: '0.03rem',
  trackingNormal: '0.05rem',
  trackingWide: '0.08rem',
  trackingDisplay: '0.12rem',
  headingMaxWidth: '44rem',
  leadMaxWidth: '43rem',
  bodySmall: '0.92rem',
  bodyBase: '1rem',
  bodyLead: 'clamp(1rem, 1.45vw, 1.15rem)',
  pageHeading: 'clamp(1.6rem, 4.2vw, 3.15rem)',
  pageLead: 'clamp(1rem, 1.5vw, 1.18rem)',
  sectionHeading: 'clamp(1.08rem, 2.3vw, 1.6rem)',
  display: 'clamp(2rem, 5vw, 4.6rem)',
  featureTitle: '0.95rem',
  meta: '0.75rem',
  lineHeightTight: '1.14',
  lineHeightHeading: '1.2',
  lineHeightBody: '1.65',
  lineHeightRelaxed: '1.7',
} as const;

export const motionTokens = {
  fast: '0.18s',
  normal: '0.2s',
  slow: '0.3s',
  easing: 'ease',
  easingEmphasized: 'cubic-bezier(0.2, 0, 0, 1)',
} as const;

export const zIndexTokens = {
  nav: 6,
  overlay: 7,
  floating: 8,
} as const;
