export const layoutTokens = {
  page: {
    top: '7.5rem',
    topCompact: '6rem',
    bottom: '7.5rem',
    bottomLarge: '9rem',
    bottomCompact: '6rem',
    detailBottom: '6.5rem',
    detailBottomCompact: '5.5rem',
  },
  container: {
    narrow: '60rem',
    content: '70rem',
    wide: '75rem',
    viewport: '96vw',
    compactViewport: '94vw',
  },
  grid: {
    cardMinWidth: '17.5rem',
    gap: '1.35rem',
    columnGap: '1.35rem',
    rowGap: '2rem',
  },
  rhythm: {
    tight: '0.9rem',
    related: '1.5rem',
    section: '3.5rem',
  },
  nav: {
    hiddenOffset: '-106px',
    mobilePanelTopOffset: '5.7rem',
    heightDesktop: '84px',
    heightMobile: '72px',
  },
} as const;

export const componentTokens = {
  home: {
    heroMinHeight: '122svh',
    heroMinHeightCompact: '112svh',
    heroBottom: '6rem',
    heroBottomCompact: '3.4rem',
    heroContentWidth: 'min(58rem, 92vw)',
    heroContentPadding: '2.5rem 1.75rem',
    heroContentPaddingCompact: '1.6rem 1.1rem',
    heroGlowWidth: 'min(72rem, 88vw)',
    heroGlowHeight: 'min(32rem, 56vw)',
    panelsTop: '2.6rem',
    panelsTopCompact: '1.8rem',
    panelsBottom: '3.2rem',
    panelsBottomCompact: '2.4rem',
    panelsGap: '1.75rem',
    heroLeadSize: 'clamp(1rem, 1.6vw, 1.28rem)',
    heroEyebrowBottom: '0.85rem',
    heroTitleBottom: '1.25rem',
    heroActionsTop: '1.65rem',
    heroActionsGap: '1rem',
    panelTitleSize: 'clamp(1.2rem, 2vw, 1.72rem)',
    panelPadding: '2.6rem',
    panelPaddingCompact: '1.9rem',
    panelTitleBottom: '1.1rem',
    panelTextBottom: '2rem',
    eyebrowTracking: '0.18rem',
    scrollHintSize: '0.66rem',
    panelTitleTracking: '0.06rem',
    panelTextMaxWidth: '42ch',
    panelMinHeight: '19rem',
    panelMinHeightCompact: '15rem',
  },
  card: {
    mediaMinHeight: '14rem',
    mediaMinHeightCompact: '12rem',
    descriptionGap: '1rem',
    descriptionPadding: '1.9rem 1.65rem 2rem',
    descriptionMinHeight: '13rem',
    titleLines: 2,
    excerptLines: 3,
    actionTopSpacing: '1.15rem',
    hoverLift: '-4px',
    titleSize: 'clamp(1.3rem, 1.8vw, 1.9rem)',
    metaSize: '0.72rem',
    metaTracking: '0.14rem',
    actionSize: '0.82rem',
    actionTracking: '0.08rem',
  },
  overlay: {
    sideRailWidth: '70px',
    contentWidthOffset: '140px',
    toastBottomOffset: '1rem',
    toastWidth: 'min(32rem, calc(100vw - 2rem))',
    toastMinHeight: '3rem',
    lightPadding: '1rem',
  },
  gallery: {
    tileMinWidth: '16rem',
    tileAspectPadding: '66%',
    topOffset: '2rem',
  },
  about: {
    heroGap: '1.6rem',
    heroMediaAspect: '5 / 6',
    heroMediaAspectCompact: '4 / 5',
    heroMediaMinHeight: '28rem',
    heroMediaMinHeightCompact: '16rem',
    heroToSectionsTop: '6rem',
    betweenSectionsTop: '5rem',
    sectionGap: '1.9rem',
    heroPanelPadding: '2.4rem',
    leadTop: '1.1rem',
    actionsTop: '1.8rem',
    actionsGap: '1rem',
    sectionTextTop: '1rem',
    valuesTitleBottom: '1.1rem',
    valueCardPadding: '2rem 1.6rem',
    valueTextTop: '0.6rem',
    sectionCardMinWidth: '18rem',
    valueCardMinWidth: '16rem',
  },
  contacts: {
    infoGridLeft: 'minmax(0, 0.86fr)',
    infoGridRight: 'minmax(0, 1.14fr)',
    heroBottom: '3.5rem',
    gridGap: '1.75rem',
    panelPadding: '2.3rem 2rem',
    panelPaddingCompact: '1.65rem 1.4rem',
    listGap: '1.3rem',
    actionGap: '1.1rem',
    stepSize: '2.15rem',
    formHintSize: '0.84rem',
    listTop: '1.15rem',
    itemGap: '0.85rem',
    linksTop: '1.8rem',
    formIntroTop: '0.9rem',
    missingKeyTop: '1.1rem',
  },
  surface: {
    softPadding: '2rem 1.75rem',
    mutedPadding: '1.75rem 1.5rem',
  },
  action: {
    smPadding: '0.62rem 1rem',
    mdPadding: '0.75rem 1.2rem',
    smSize: '0.8rem',
    mdSize: '0.84rem',
    smTracking: '0.06rem',
    mdTracking: '0.07rem',
    squareMinWidth: '9rem',
    squareMinHeight: '3rem',
    squareTracking: '0.04rem',
    hoverLiftPrimary: '-2px',
    hoverLiftDefault: '-1px',
  },
  form: {
    fieldMinHeight: '2.9rem',
    textareaMinHeight: '11rem',
    fieldPadding: '0.75rem',
    buttonMinWidth: '8.5rem',
    buttonTracking: '0.08rem',
    focusRingWidth: '3px',
  },
  nav: {
    brandTracking: '0.16rem',
    linkSizeDesktop: '0.92rem',
    linkSizeMobile: '1.15rem',
    linkTrackingDesktop: '0.04rem',
    linkTrackingMobile: '0.05rem',
    linkHeightDesktop: '2.35rem',
    linkHeightMobile: '2.8rem',
    linkPaddingDesktop: '0.5rem 0.75rem',
    linkPaddingMobile: '0.75rem 1rem',
  },
  footer: {
    titleTracking: '0.12rem',
    linkTracking: '0.06rem',
    footnoteTracking: '0.03rem',
  },
  detail: {
    backMinWidth: '10.4rem',
    titleTop: '1.1rem',
    leadTop: '1.1rem',
    metaTop: '1rem',
    metaTracking: '0.08rem',
    metaSize: '0.75rem',
    gridGap: '1.5rem',
    mediaMinHeight: '24rem',
    mediaMinHeightCompact: '16rem',
    descriptionPadding: '2rem 2rem',
    descriptionHeadingTop: '1.3rem',
    descriptionHeadingBottom: '0.75rem',
    descriptionHeadingTracking: '0.04rem',
    paragraphSpacing: '1rem',
    listVerticalSpacing: '1.1rem',
    listIndent: '1.2rem',
    sectionTitleTracking: '0.08rem',
    sectionTitleBottom: '1.1rem',
  },
  listing: {
    sectionGap: '4rem',
    cardsToCtaTop: '3.25rem',
    ctaTextMaxWidth: '44ch',
    ctaLinkMinWidth: '10.5rem',
  },
  iconButton: {
    size: '2.7rem',
    topOffset: '1.25rem',
    lineWidth: '1.3rem',
    lineThickness: '2px',
    lineTopStart: '0.86rem',
    lineTopCenter: '1.28rem',
    lineTopEnd: '1.7rem',
  },
} as const;

export const typographyTokens = {
  eyebrowSize: '0.74rem',
  labelStrong: '0.84rem',
  eyebrowTracking: '0.12rem',
  trackingTight: '0.01rem',
  trackingNormal: '0.03rem',
  trackingWide: '0.06rem',
  trackingDisplay: '0.08rem',
  headingMaxWidth: '46rem',
  leadMaxWidth: '44rem',
  bodySmall: '0.92rem',
  bodyBase: '1rem',
  bodyLead: 'clamp(1.05rem, 1.5vw, 1.18rem)',
  pageHeading: 'clamp(1.5rem, 3.6vw, 2.7rem)',
  pageLead: 'clamp(1rem, 1.5vw, 1.18rem)',
  sectionHeading: 'clamp(1.15rem, 2.4vw, 1.75rem)',
  display: 'clamp(2rem, 4.4vw, 4rem)',
  featureTitle: '1.05rem',
  meta: '0.75rem',
  lineHeightTight: '1.16',
  lineHeightHeading: '1.22',
  lineHeightBody: '1.68',
  lineHeightRelaxed: '1.72',
} as const;

export const motionTokens = {
  fast: '0.18s',
  normal: '0.2s',
  slow: '0.3s',
  easing: 'ease',
  easingEmphasized: 'cubic-bezier(0.2, 0, 0, 1)',
} as const;

export const zIndexTokens = {
  nav: 6,
  overlay: 7,
  floating: 8,
} as const;
